# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

#Nome da Rotina a se executada
name: Go

#Defini quando deve ser executada a rotina que está rodando,
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#São os passos a passos para executar as tarefas e concluir
jobs: 

##############################################    ---  DOCKER   ---   ##############################################   
  docker-DB:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ['>=1.8', '1.18', '1.17']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
    
    #Criação do Banco de Dados e command para execução
    - name: Build-DB
      run: docker-compose build
      
    #Copilação do Banco de Dados e command para execução
    - name: Create-DB
      run: docker-compose up -d
      
##############################################    ---  TEST   ---   ##############################################      

#Uma das tarefas a ser executadas e configuradas
  test:
  #Tarefa que sera executada de Bulid - ultima versão do ubuntu
    needs: docker-DB
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    #Execução dos testes e o command para execução
    - name: Test
      run: go test -v main_test.go
      
##############################################    ---  BUILD   ---   ##############################################
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    #Copilação do Codigo e command para execução
    - name: Build
      run: go build -v main.go
      
      
      
